name: Deploy to Firebase

on:
  push:
    branches:
      - development
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean npm artifacts
        run: |
          rm -rf node_modules
          # rm -f package-lock.json  # Remova ou comente essa linha para manter o lock file

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Development
        if: github.ref == 'refs/heads/develop'
        run: firebase deploy --project=ads-representacoes-dev --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: firebase deploy --project=ads-representacoes --token ${{ secrets.FIREBASE_TOKEN }}
